### ISSUE TITLE
朱博士您好，非常希望能够获取您Usenix-2020的数据集，但是原文链接已经无法访问，不知道能否麻烦您进行分享，万分感谢

### ISSUE THREAD

**Issue by Gray-byte** [sfzhu93/sfzhu93.github.io#1]
朱博士您好，非常希望能够获取您Usenix-2020的数据集，但是原文链接已经无法访问，不知道能否麻烦您进行分享，万分感谢

**Comment by sfzhu93** [comment]
Thanks for your interest in the dataset! We made the dataset as a [separate tool](https://zenodo.org/record/3978705#.ZFLOstLMJD8).

**Comment by Gray-byte** [comment]
> Thanks for your interest in the dataset! We made the dataset as a [separate tool](https://zenodo.org/record/3978705#.ZFLOstLMJD8).

Thank you so much for your reply，best wishes to you
